ex0 = ('')

ex003 = ('Somando ois números')
ex004 = ('Dissecando uma variável')
ex005 = ('Antecesor e sucessor')
ex006 = ('Dobro, triplo, raiz quadrada')
ex007 = ('Média aritmética')
ex008 = ('Conversor de medidas')
ex009 = ('Tabuada')
ex010 = ('Conversor de moedas')
ex011 = ('Pintando parede')
ex012 = ('Calculando descontos')
ex013 = ('Reajuste salarial')
ex014 = ('Conversor de Temperaturas')
ex015 = ('Aluguel de carros')

ex054 = ('Grupo da maioridade')
ex055 = ('Maior e menor da sequência')
ex056 = ('Analisador completo')
ex057 = ('Validação de dados')
ex058 = ('Jogo da adivinhação')
ex059 = ('Criando um menu de opções')
ex060 = ('Cálculo do fatorial')
ex061 = ('Progressão aritmética')
ex062 = ('Super progressão aritimética')
ex063 = ('Sequência de Finonacci')
ex064 = ('Tratando vários valores')
ex065 = ('Maior e menor valores')
ex066 = ('Vários números com flag')
ex067 = ('Tabuada v3.0')

